apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    {{- if .Values.externalSecret }}
    {{- if .Values.externalSecret.forceSyncTimestamp }}
    force-sync: "{{ .Values.externalSecret.forceSyncTimestamp }}"
    {{- end }}
    {{- end }}
  name: {{ template "leo.fullname" . }}
  labels:
    app: {{ template "leo.name" . }}
    chart: {{ template "leo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secretsmanagersecrets
  target:
    name: {{ template "leo.fullname" . }}
  dataFrom:
    - extract:
        key: {{ .Values.leo.environment }}/leo/environment
        decodingStrategy: None

